name: Run E2E Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

  services:
   postgres:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      env:
        - POSTGRESQL_USERNAME=docker
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=apiGympass

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/gympass-api-node-api-gympass-pg-1?schema=public"
          JWT_SECRET: testing